
import "./globals.css";

import localFont from '@next/font/local'
import Footer from "./components/footer/Footer";
import Header from "./components/header/Header";


const soehne = localFont({
  
    src:[{
      path:"../../public/fonts/._test-soehne-buch.woff2"
    },
  
],
variabe:"--font-soehne"
  
})

export const metadata = {
  title: "Alkye services",
  description: "Default Discription Generated by Next JS",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${soehne.variabe}`}>
      <body className="font-soehne">
      
         <div>{children}</div>
          <p>&nbsp;</p>
         <div><Footer /></div>



      </body>
    </html>
  );
}
